// This file is auto-generated by TanStack Router

import { Route as rootRoute } from './routes/__root'
import { Route as SignupRoute } from './routes/signup'
import { Route as SigninRoute } from './routes/signin'
import { Route as PricingRoute } from './routes/pricing'
import { Route as LucyRoute } from './routes/lucy'
import { Route as IndexRoute } from './routes/index'
import { Route as EbookMachineRoute } from './routes/ebook-machine'

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexRoute
      parentRoute: typeof rootRoute
    }
    '/lucy': {
      preLoaderRoute: typeof LucyRoute
      parentRoute: typeof rootRoute
    }
    '/pricing': {
      preLoaderRoute: typeof PricingRoute
      parentRoute: typeof rootRoute
    }
    '/signin': {
      preLoaderRoute: typeof SigninRoute
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupRoute
      parentRoute: typeof rootRoute
    }
    '/ebook-machine': {
      preLoaderRoute: typeof EbookMachineRoute
      parentRoute: typeof rootRoute
    }
  }
}

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LucyRoute,
  PricingRoute,
  SigninRoute,
  SignupRoute,
  EbookMachineRoute,
])
